### ISSUE TITLE
startConversation() is throwing an InvokeTargetException: null

### ISSUE THREAD

**Issue by AtbTheGreat** [ramswaroop/jbot#63]
I have a new issue now. When I call `startConversation()` in my java method `init()`, it throws an `InvokeTargetException` even though the string parameter I am using is a method that actually exists. Here is a snippet of my bot code (feel free to correct any other ways in which I'm using your framework wrong, if that's the case):

```
@Controller(events=EventType.USER_TYPING, next="promptQuestion")
    public void init(WebSocketSession session, Event event) {
      if(rightTime() == true){ // Bot does nothing if it's not the right time/circumstances to ask questions
        initializeReaderAndWriter();
        startConversation(event, "promptQuestion");
      }
    }


@Controller(next="promptQuestion")
    public void promptQuestion(WebSocketSession session, Event event) {
       String question = ""; // initialize question
       try{
         question = questionReader.readLine(); // read the current question from the text file "questions.txt"
       }
       catch(IOException e){
         e.printStackTrace();
       }
      reply(session, event, new Message(question)); // print out the most recently read question
      answerWriter.println(event.getText()); // take in the user's answer to that question
      if( (++answerCount) < 3) nextConversation(event); // Repeat the method if this is only the first or second question
      else{ // If it's the third (last) question, end the conversation
        try{
          questionReader.close(); // The feature (reader) that reads the question file must close after asking all three questions
          answerWriter.close(); // The feature that saves the answers to a text file must also close after the user is finished giving out his/her
          // three answers
        }
        catch(IOException e){
         e.printStackTrace();
       }
        stopConversation(event); // No more calling of promptQuestion() until the next day
      }
    }

```

Here is the exception/error output:
```
2017-07-17 11:19:51.555 ERROR 10932 --- [ient-SecureIO-1] me.ramswaroop.jbot.core.slack.Bot        : Error invoking controller:

java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
        at me.ramswaroop.jbot.core.slack.Bot.invokeMethods(Bot.java:304) [jbot-3.0.2.jar:3.0.2]
        at me.ramswaroop.jbot.core.slack.Bot.handleTextMessage(Bot.java:177) [jbot-3.0.2.jar:3.0.2]
        at me.ramswaroop.jbot.core.slack.BotWebSocketHandler.handleTextMessage(BotWebSocketHandler.java:32) [jbot-3.0.2.jar:3.0.2]
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) [spring-web
socket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) [spring-w
ebsocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java
:56) [spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerA
dapter.java:110) [spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.
java:42) [spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter
.java:81) [spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter
.java:78) [spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:399) [tomcat-embed-websocket-8.5.4.jar:8.5.4]
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:500) [tomcat-embed-websocket-8.5.4.jar:8.5.4]
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:295) [tomcat-embed-websocket-8.5.4.jar:8.5.4]
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131) [tomcat-embed-websocket-8.5.4.jar:8.5.4]
        at org.apache.tomcat.websocket.WsFrameClient.processSocketRead(WsFrameClient.java:73) [tomcat-embed-websocket-8.5.4.jar:8.5.4]
        at org.apache.tomcat.websocket.WsFrameClient.access$300(WsFrameClient.java:31) [tomcat-embed-websocket-8.5.4.jar:8.5.4]
        at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:131) [tomcat-embed-we
bsocket-8.5.4.jar:8.5.4]
        at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:114) [tomcat-embed-we
bsocket-8.5.4.jar:8.5.4]
        at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WrapperFuture.complete(AsyncChannelWrapperSecure.java:463) [tomcat-em
bed-websocket-8.5.4.jar:8.5.4]
        at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$ReadTask.run(AsyncChannelWrapperSecure.java:332) [tomcat-embed-websoc
ket-8.5.4.jar:8.5.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.lang.StackOverflowError: null
        at me.ramswaroop.jbot.core.slack.Bot.formConversationQueue(Bot.java:270) [jbot-3.0.2.jar:3.0.2]
        at me.ramswaroop.jbot.core.slack.Bot.formConversationQueue(Bot.java:275) [jbot-3.0.2.jar:3.0.2]
        at me.ramswaroop.jbot.core.slack.Bot.formConversationQueue(Bot.java:275) [jbot-3.0.2.jar:3.0.2]
        at me.ramswaroop.jbot.core.slack.Bot.formConversationQueue(Bot.java:275) [jbot-3.0.2.jar:3.0.2]
        at me.ramswaroop.jbot.core.slack.Bot.formConversationQueue(Bot.java:275) [jbot-3.0.2.jar:3.0.2]`
```

**Comment by gclouds** [comment]
how did you solved this problem?
