### ISSUE TITLE
jbot slack + spring boot

### ISSUE THREAD

**Issue by cicero-barros** [ramswaroop/jbot#74]
I'm trying to user jbot with Spring Boot but i'm getting this error when a run the project

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-09-20 15:24:11.880 ERROR 16508 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field slackService in me.ramswaroop.jbot.core.slack.Bot required a bean of type 'me.ramswaroop.jbot.core.slack.SlackService' that could not be found.

Action:

Consider defining a bean of type 'me.ramswaroop.jbot.core.slack.SlackService' in your configuration.

**Comment by ramswaroop** [comment]
I think you didn't fork the project. If you can fork and commit your changes to your fork, I will be able to help. But from your error message, it seems, `SlackService` bean isn't created. It may be because you removed some annotation or the Spring config is incorrectly configured.

**Comment by mmaxine** [comment]
Try configuring your spring boot application to scan for that package, something like:
@SpringBootApplication(scanBasePackages = {
	"me.ramswaroop.jbot",
	"com.your.package"
})

**Comment by ivanskodje** [comment]
Sorry to bump on this, however I have the same problem. By doing what suggested by @mmaxine , I get a new error:
```java

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fbApiEndpoints': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'fbGraphApi' in value "${fbGraphApi}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:376)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1336)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:572)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.XXXXX.Application.main(Application.java:25)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'fbGraphApi' in value "${fbGraphApi}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:237)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:211)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:839)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1083)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:581)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
	... 15 common frames omitted


Process finished with exit code 1
```

**Comment by shshenG** [comment]
@ivanskodje @mmaxine @cicero-barros have you seen this error before? 
https://github.com/rampatra/jbot/issues/146
